### PR TITLE
Full Reference Documentation

### PR DESCRIPTION
**Pull request by cavalle**
* This PR adds full API reference documentation to the library using YARD
* It's a large PR, it might be easier to digest commit by commit
* Every public module, class, method, constant and attribute is now documented, including those of generated classes (using the descriptions in the JSON schema). Basically, only the intermediate namespaces in the hierarchy (such as `GOBL::Num`or `GOBL::Bill`) doesn't have any documentation. If, in the future, we find a way to describe those namespaces in the schema, we could add them here too. `GOBL::L10n::CountryCode` is missing too because there's no description in the JSON schema; I'll fix that and add it here in a separated PR.
* README is outdated. I'll update it in a separated PR.
* [Update] The documentation is public (using this branch, at the moment) here: https://rubydoc.info/github/invopop/gobl.ruby

```
# yard stats --list-undoc --compact --quiet
Files:          95
Modules:        23 (   17 undocumented)
Classes:        89 (    1 undocumented)
Constants:      91 (    0 undocumented)
Attributes:    151 (    0 undocumented)
Methods:       424 (    0 undocumented)
 97.69% documented

Undocumented Objects:
GOBL::Bill                                          (lib/gobl/bill/tax.rb:11)
GOBL::Cal                                           (lib/gobl/cal/date.rb:11)
GOBL::Currency                                      (lib/gobl/currency/code.rb:11)
GOBL::DSig                                          (lib/gobl/dsig/digest.rb:11)
GOBL::I18n                                          (lib/gobl/i18n/string.rb:11)
GOBL::L10n                                          (lib/gobl/l10n/code.rb:11)
GOBL::L10n::CountryCode                             (lib/gobl/l10n/country_code.rb:12)
GOBL::Note                                          (lib/gobl/note/message.rb:11)
GOBL::Num                                           (lib/gobl/num/amount.rb:4)
GOBL::Org                                           (lib/gobl/org/key.rb:11)
GOBL::Pay                                           (lib/gobl/pay/card.rb:11)
GOBL::Tax                                           (lib/gobl/tax/set.rb:11)
GOBL::UUID                                          (lib/gobl/uuid/uuid.rb:11)
GOBLExtensions                                      (lib/gobl_extensions/document_helper.rb:1)
GOBLExtensions::DocumentHelper::ClassMethods        (lib/gobl_extensions/document_helper.rb:32)
GOBLExtensions::I18n                                (lib/gobl_extensions/i18n/value_keys_helper.rb:4)
GOBLExtensions::Tax                                 (lib/gobl_extensions/tax/region_helper.rb:6)
GOBLExtensions::Tax::RegionHelper::ClassMethods     (lib/gobl_extensions/tax/region_helper.rb:9)
```

### CODE REVIEW

**Review by samlown — APPROVED** [review]
This one is indeed massive 😆 From the outside it looks sound. Is there a public link we can share?

**Comment by cavalle** [comment]
Not yet a public link. I'd say we need the README first (will come very soon!). Also, I'm not sure where to publish it. The obvious option is https://rubydoc.info where most RubyGems docs are available, but lately it's quite slow. Do you have any preference, @samlown?

**Comment by cavalle** [comment]
Just added this branch to RubyDoc.info: https://rubydoc.info/github/invopop/gobl.ruby

**Comment by samlown** [comment]
Cool! In Rubydoc it does indeed take a while to load, but looks pretty complete! nice!

**Pull request merged**
