### PR TITLE
add generator for markdown documentation

### PR DESCRIPTION
**Pull request by MarkVillacampa**

### CODE REVIEW

**Comment by cavalle** [comment]
Glad to see the generator used for something else than Ruby. That said, I cannot help but feel the Ruby gem is not right place for the generator to live now that it generates more than Ruby code. At the end of the day, Ruby code is just one of the targets of the generator.

Anyways, I suppose at some point we will have to extract, but I also think it's too early for it. All I'd do for the moment is "gitignoring" the `docs/` folder as we're not suppose to commit the generated docs in this repo.

**Comment by samlown** [comment]
@cavalle inclined to agree, perhaps we should separate the generator out into it's own project?

**Comment by cavalle** [comment]
Not sure why this PR was still open, but it seems to me we can close it now. Everything is in `gobl.generator` now. Wdyt?

**Comment by samlown** [comment]
Sounds good! I'll close.

**Pull request closed without merging**
